#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 102133lxy
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis本地服务器地址，注意要开启redis服务，即那个redis-server.exe
    host: 127.0.0.1
    # Redis服务器端口,默认为6379.若有改动按改动后的来
    port: 6379
    #Redis服务器连接密码，默认为空，若有设置按设置的来
    password:
    jedis:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 8
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
#实体类别名
mybatis:
  type-aliases-package: com.org.mollcol.mapper
  #映射文件的位置
  mapper-locations: classpath:mapper/*.xml

#日志配置
logging:
  level:
    com.org.mollcol.mapper: debug

#设置mybatis-plus的日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



